version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/code.mumak.net
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            python -m virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Fetch plugins
          command: git clone git@github.com:getpelican/pelican-plugins.git plugins
      - run:
          name: Fetch themes
          command: git clone git@github.com:getpelican/pelican-themes.git themes
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Build website
          command: |
            . venv/bin/activate
            make publish
      - persist_to_workspace:
          root: output
          paths:
            - "*"

  deploy:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/code.mumak.net
    steps:
      - run:
          name: Install AWS client
          command: pip install --upgrade --user awscli
      - attach_workspace:
          at: output
      - run:
          name: Upload to S3
          command: aws s3 sync --acl public-read --delete output/ s3://jml.io

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
